# Generated by Django 5.2.7 on 2025-11-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbname', models.CharField(max_length=25)),
                ('mbim', models.FileField(upload_to='pic')),
                ('prc', models.IntegerField()),
                ('dec', models.TextField()),
            ],
        ),
    ]
